
export default {
    TICK: 'TICK',
    LOGIN: 'LOGIN',
    COLORNUMBERPROFILE: 'COLORNUMBERPROFILE',
    COLORNAMEPROFILE: 'COLORNAMEPROFILE',
    HANDLENUMBERPROFILE: 'HANDLENUMBERPROFILE',
    HANDLENAMEPROFILE: 'HANDLENAMEPROFILE',

    COLORNUMBERCOMPOSITE: 'COLORNUMBERCOMPOSITE',
    COLORNAMECOMPOSITE: 'COLORNAMECOMPOSITE',
    HANDLENUMBERCOMPOSITE: 'HANDLENUMBERCOMPOSITE',
    HANDLENAMECOMPOSITE: 'HANDLENAMECOMPOSITE',

    COLORNUMBERFINANCIAL: 'COLORNUMBERFINANCIAL',
    COLORNAMEFINANCIAL: 'COLORNAMEFINANCIAL',
    HANDLENUMBERFINANCIAL: 'HANDLENUMBERFINANCIAL',
    HANDLENAMEFINANCIAL: 'HANDLENAMEFINANCIAL',

    COLORNUMBERKYC: 'COLORNUMBERKYC',
    COLORNAMEKYC: 'COLORNAMEKYC',
    HANDLENUMBERKYC: 'HANDLENUMBERKYC',
    HANDLENAMEKYC: 'HANDLENAMEKYC',

    COLORNUMBERNEWS: 'COLORNUMBERNEWS',
    COLORNAMENEWS: 'COLORNAMENEWS',
    HANDLENUMBERNEWS: 'HANDLENUMBERNEWS',
    HANDLENAMENEWS: 'HANDLENAMENEWS',

    COLORNUMBERPEERCOMPOS: 'COLORNUMBERPEERCOMPOS',
    COLORNAMEPEERCOMPOS: 'COLORNAMEPEERCOMPOS',
    HANDLENUMBERPEERCOMPOS: 'HANDLENUMBERPEERCOMPOS',
    HANDLENAMEPEERCOMPOS: 'HANDLENAMEPEERCOMPOS',

    COLORNUMBERPREDICTIVE: 'COLORNUMBERPREDICTIVE',
    COLORNAMEPREDICTIVE: 'COLORNAMEPREDICTIVE',
    HANDLENUMBERPREDICTIVE: 'HANDLENUMBERPREDICTIVE',
    HANDLENAMEPREDICTIVE: 'HANDLENAMEPREDICTIVE',

    COLORNUMBERWEB: 'COLORNUMBERWEB',
    COLORNAMEWEB: 'COLORNAMEWEB',
    HANDLENUMBERWEB: 'HANDLENUMBERWEB',
    HANDLENAMEWEB: 'HANDLENAMEWEB',

    COLORNUMBERRISK: 'COLORNUMBERRISK',
    COLORNAMERISK: 'COLORNAMERISK',
    HANDLENUMBERRISK: 'HANDLENUMBERRISK',
    HANDLENAMERISK: 'HANDLENAMERISK',
}